//App error

export const INIT_APP = 'INIT_APP';
export const INIT_APP_ERROR = 'INIT_APP_ERROR';

//firebase
export const FIREBASE_INIT = 'FIREBASE_INIT';
export const FIREBASE_INIT_ERROR = 'FIREBASE_INIT_ERROR';

//Async call
export const BEGIN_ASYNC_CALL = 'BEGIN_ASYNC_CALL';


export const CREATE_USER = 'CREATE_USER';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

//snackbar
export const SHOWING_SNACKBAR = 'SHOWING_SNACKBAR';
