//App error

export const INIT_APP = 'INIT_APP';
export const INIT_APP_ERROR = 'INIT_APP_ERROR';

//firebase
export const FIREBASE_INIT = 'FIREBASE_INIT';
export const FIREBASE_INIT_ERROR = 'FIREBASE_INIT_ERROR';

//Async call
export const BEGIN_ASYNC_CALL = 'BEGIN_ASYNC_CALL';


export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

//snackbar
export const SHOWING_SNACKBAR = 'SHOWING_SNACKBAR';

//Dialogwindow
export const SHOWING_DIALOG = 'SHOWING_DIALOG';

//user actions
//team
export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';
//device
export const CREATE_DEVICE = 'CREATE_DEVICE';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_ERROR = 'CREATE_DEVICE_ERROR';

export const MENU_ITEM_CLICK = 'MENU_ITEM_CLICK';
